name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
          cache-version: 0
      - name: Change directory to wiki
        run: cd wiki
      - name: Install dependencies
        run: bundle install
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "/mediumish-theme-jekyll/wiki"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: wiki/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site
          path: wiki/_site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
